### ISSUE TITLE
Error of selecting residue 

### ISSUE THREAD

**Issue by nthpham** [mabr3112/riff_diff_protflow#12]
Hello,
I specify the residues to select as instruction :
--theozyme_resnums 23A,88A,124A,129A

However, I receive this error while running identify_fragments.py . What could be the issue and how could I fix it ?

Traceback (most recent call last):
  File "/home/nthpham/applications/riff_diff_protflow/identify_fragments.py", line 1613, in <module>
    main(args)
  File "/home/nthpham/applications/riff_diff_protflow/identify_fragments.py", line 1273, in main
    theozyme_residue = theozyme[0][chain][resnum]
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/nthpham/applications/ProtFlow/protflow_env/lib/python3.11/site-packages/Bio/PDB/Chain.py", line 113, in __getitem__
    return Entity.__getitem__(self, id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nthpham/applications/ProtFlow/protflow_env/lib/python3.11/site-packages/Bio/PDB/Entity.py", line 65, in __getitem__
    return self.child_dict[id]
           ~~~~~~~~~~~~~~~^^^^
KeyError: (' ', 23, ' ')

**Comment by TecnomaLaser** [comment]
Hi,
can you upload your PDB somewhere? Are you sure there is a residue 23 on chain A?
I'll add an error message if the residue is not present.
Cheers

**Comment by nthpham** [comment]
Yes, I have residue on chain A. It seems that I can't attach pdb file here. So I just sent you the pdb file to your email.
Best
